Comment, Post Users 엔티티 1:N 연관관계 매핑 및 카카오 로그인 사전 구현
sidesideproject/seniors-server pull request #16
Opened 2023-07-04 05:46 UTC by uiurihappy

## 📕 제목
Comment, Post Users 엔티티 1:N 연관관계 매핑 및 카카오 로그인 사전 구현

## 📗 작업 내용

> 구현 내용 및 작업 했던 내역

- [x] Comment, Post의 Users 1:N 관계 매핑  
- [x] 매핑 과정 중 users 정보를 어떻게 가져와야 하나 고민하다가 카카오 로그인 사전 구현
- [x] Spring Security 적용

## 📘 PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- com.seniors.auth 폴더를 새로 생성하여 로그인/회원가입 로직을 위한 interface, class를 설계
- Spring Security를 적용했기에 Security Config 유심히 보고 수정할 여지가 있으면 수정
- Security Config에 permitAllUrl String[] 에 본인 작업한 API url이 존재하면 path 추가할 것

2023-07-04 12:07 UTC, strangehoon requested changes
1. 이슈가 현재 "Comment, Post 엔티티 Users와 1:N 연관관계 매핑 #11" 로 되어 있는데 이슈명을 소셜 로그인 구현으로 바꿔주시면 좋을 거 같습니다. 
2.  저희 Junit으로 테스트코드 작성하기로 했었는데 테스트코드 부분이 빠져있는거 같습니다. 3. 저도 소셜 로그인 부분을 잘 알지는 못하는데 아마 나중에 CORS가 터질수도 있을거 같습니다. 
4.  auth 폴더를 domain 폴더 안으로 넣고 security 폴더를 config 폴더 안에 넣고 기존의 securityConfig 파일을 다시 security 폴더에 넣는거 어떨지 제안해봅니다!

2023-07-04 12:35 UTC, uiurihappy commented on src/main/java/com/seniors/auth/controller/AuthController.java
> +	@PostMapping("/kakao")
1번은 반영했습니다!
테스트 코드도 추가해서 반영하겠습니다!
cors는 아마 WebMvcConfig에서 설정이 가능한 걸로 아는데 프론트엔드의 도메인이나 port 번호가 받아지면 cors 설정하도록 하겠습니다.
4번 사항도 반영해놓겠습니다. 아까 merge하다가 충돌이 나서 저 부분을 누락했었네요

oauth/kakao/callback 인거는 알고 있었는데 아직 정확히 카카오 애플리케이션 등록하고 추후에 수정을 해야할 거 같습니다.

제가 답변한 내용들은 수정해서 다시 올리도록 하겠습니다.

2023-07-04 12:49 UTC, strangehoon commented on src/main/java/com/seniors/auth/controller/AuthController.java
> +	@PostMapping("/kakao")
넵넵 고생하십니다!! 저는 저번에 cors를 spring security에서 설정했었습니다!! 두가지 방법이 있는거 같더라구요 ㅎㅎ

2023-07-04 13:05 UTC, uiurihappy commented on src/main/java/com/seniors/auth/controller/AuthController.java
> +	@PostMapping("/kakao")
.requestMatchers(CorsUtils::isPreFlightRequest).permitAll()
이 코드가 해결해주네요 덕분에 하나 알아갑니다 ㅎㅎㅎ

2023-07-05 12:03 UTC, regchoi reviewed
고생하셨습니다~!

2023-07-05 13:02 UTC, strangehoon reviewed
연관관계 위주로만 확인했습니다!! 리뷰할때 너무 다양한 도메인이 섞여있어서ㅠㅠ 다음부터는 이슈에 맞추어서 pr 날려주시면 감사하겠습니다.

2023-07-05 14:30 UTC, uiurihappy commented on src/main/java/com/seniors/domain/comment/Comment.java
> +	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
아 이건 잘못됐네요..!  orphanRemoval = true 이걸 썼어야 했는데 실수했습니다! 수정할게요.

2023-07-05 14:36 UTC, uiurihappy commented on src/main/java/com/seniors/domain/comment/Comment.java
> +	private Users users;
@JsonIgnore를 안하면
Response already committed. Ignoring: org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: Infinite recursion (StackOverflowError)
이와 같은 에러가 발생되요..!

직렬화 과정을 무시해야 하는 게 객체간의 순환참조가 되어 무한 재귀가 발생되요ㅜ 그래서 무한 재귀 방지 정도 생각하시면 될 듯합니다!

2023-07-06 04:11 UTC, strangehoon commented on src/main/java/com/seniors/domain/comment/Comment.java
> +	private Users users;
저 같은 경우에는 예전에 service단과 controller 단에서 return 값을 DTO가 아닌 Entity로 설정해서 양방향 무한 참조 에러가 떴었거든요,  제가 보기에는 윤범님께서 service단과 controller 단에서 return 값을 entity로 설정한건 안보이는데 제가 생각하기에는 테스트코드 작성하시다가 엔티티를 반환해서 에러가 터지시는거 같네요. 저는 아직 테스트코드를 잘 몰라서 자세히는.... 저는 @JsonIgnore를 엔티티에서 써본적은 없는데 쓰면 comment 엔티티안의 users 컬럼에 null 값이 들어가니까 안되는거 아닌가요??

2023-07-06 05:04 UTC, uiurihappy commented on src/main/java/com/seniors/domain/comment/Comment.java
> +	private Users users;
음...
저도 JsonIgnore를 딥하게 알아보지는 못해서 좀 더 연구해보겠습니다

2023-07-06 05:18 UTC, uiurihappy commented on src/main/java/com/seniors/domain/comment/Comment.java
> +	private Users users;
아무래도 Dto를 사용해서 객체를 재구성하여 return 받을 수 있도록 해야할 듯 합니다....
알려주셔서 감사합니다:)

2023-07-07 01:04 UTC, merged